### ISSUE TITLE
Despite api_enable_users being set to True, an update is always generated by Pulumi

### ISSUE THREAD

**Issue by damey2011** [pulumi/pulumi-auth0#445]
### What happened?

Using Pulumi Python, I create an Auth0 connection with attribute `api_enable_users` being set to `true`, but everytime I run `pulumi up` or `pulumi preview`, there's a change from `false` to `true` needing to be applied.

### Example

```
auth_connection = auth0.Connection(
    f"{a0_settings.CURRENT_ENV}-auth",
    strategy="auth0",
    options=auth0.ConnectionOptionsArgs(
        disable_signup=True,
        api_enable_users=True,
        brute_force_protection=True
    ),
    opts=opts
)
```

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::pressone-infra::pulumi:pulumi:Stack::infra-staging]
    ~ auth0:index/connection:Connection: (update)
        [id=con_GtgKWo5Er2DmXQ3N]
        [urn=urn:pulumi:staging::pressone-infra::auth0:index/connection:Connection::staging-auth]
        [provider=urn:pulumi:staging::pressone-infra::pulumi:providers:auth0::staging-auth0-provider::0a74e747-fb37-4ca1-8e30-40773071cb1a]
      ~ options: {
          ~ apiEnableUsers: false => true
        }

```

### Output of `pulumi about`

```
CLI          
Version      3.88.1
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
auth0         3.1.2
digitalocean  4.25.2
kubernetes    4.8.1
python        unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in python: executable='/Users/theoluwanifemi/Library/Caches/pypoetry/virtualenvs/infra-_cUdUW92-py3.11/bin/python3' version='3.11.6'

Current Stack: pressone/pressone-infra/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pressone
User           pressone
Organizations  pressone
Token type     personal

Dependencies:
NAME                 VERSION
pip                  23.3.2
pulumi_auth0         3.1.2
pulumi_digitalocean  4.25.2
pulumi_kubernetes    4.8.1
pydantic-settings    2.2.1
setuptools           69.0.3

Pulumi locates its logs in /var/folders/xs/2w_5vpgx3cngcxfv5y9t1p7c0000gn/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @damey2011. Thanks for reporting this issue.

**Comment by iwahbe** [comment]
For provider maintainers: I have confirmed that the perpetual diff is still present on 3b48c17c6debdf87019c917cb1b9a16e0d6a8239, which includes the PRC rollout. 

We can repro in YAML with:

```yaml
name: dev-yaml
runtime: yaml
resources:
  connection:
    type: auth0:Connection
    properties:
      strategy: auth0
      options:
        disableSignup: true
        apiEnableUsers: true
        bruteForceProtection: true

# plugins:
#   providers:
#     - name: auth0
#       path: /Users/ianwahbe/go/src/github.com/pulumi/pulumi-auth0/bin
```
